# Generated by Django 4.2.16 on 2025-09-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('admissions_officer', 'Admissions Officer'), ('hostel_warden', 'Hostel Warden'), ('finance_officer', 'Finance Officer'), ('exam_controller', 'Exam Controller'), ('librarian', 'Librarian'), ('accounts_clerk', 'Accounts Clerk'), ('registrar', 'Registrar'), ('dean', 'Dean'), ('principal', 'Principal')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField()),
                ('can_access_admissions', models.BooleanField(default=False)),
                ('can_access_hostel', models.BooleanField(default=False)),
                ('can_access_finance', models.BooleanField(default=False)),
                ('can_access_exams', models.BooleanField(default=False)),
                ('can_access_library', models.BooleanField(default=False)),
                ('can_access_students', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
    ]
